server {
    server_name ayuskart.com www.ayuskart.com;

    location / {
        root /var/www/buddy_prod/current/frontend/dist;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /uploads/ {
        alias /var/www/buddy_prod/shared/uploads/;
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }

    location /api {
        proxy_pass http://localhost:5001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /socket.io/ {
        proxy_pass http://localhost:5001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /control/ {
        proxy_pass http://localhost:5003/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /voice-ws {
        proxy_pass http://localhost:5004/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/ayuskart.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/ayuskart.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = www.ayuskart.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = ayuskart.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name ayuskart.com www.ayuskart.com;
    return 404; # managed by Certbot
}
